version: '3.8'

services:
  app:
    build: .
    container_name: fos
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5433/fos-auth-db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "9000:9000"
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    container_name: fos-auth-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: fos-auth-db
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - library-network
