version: '3.8'

services:
  app:
    build: .
    container_name: fos
    environment:
      SPRING_DATASOURCE_URL: jdbc:h2:mem:authdb
      SPRING_DATASOURCE_DRIVERCLASSNAME: org.h2.Driver
      SPRING_DATASOURCE_USERNAME: sa
      SPRING_DATASOURCE_PASSWORD: passw0rd
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.H2Dialect
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_H2_CONSOLE_ENABLED: "true"
    ports:
      - "9000:9000"
